language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
branches:
  only:
    - master
before_script:
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:schema:load'"
script: "bundle exec rspec spec"
