name: domains
engine_name: alchemy_domains
order: 1
navigation:
  name: modules.domains
  controller: /admin/domains
  action: index
  image: /assets/module_icon.png
  sub_navigation:
    - name: domains
      controller: /admin/domains
      action: index