name: domains
engine_name: alchemy
order: 1
navigation:
  name: modules.domains
  controller: alchemy/admin/domains
  action: index
  image: /assets/module_icon.png
  sub_navigation:
    - name: domains
      controller: alchemy/admin/domains
      action: index
